// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://smartattendance.fastwebcm.local/api/v1' | (string & {});
};

export type UserType = 'student' | 'staff';

export type UserStatus = 'active' | 'inactive' | 'dismissed';

export type BiometricEnrollmentStatus = 'pending' | 'completed';

export type Login = {
    username: string;
    password: string;
    stayloggedin?: boolean;
};

export type LoginResponse = {
    success?: boolean;
    accessToken?: string;
    user?: {
        id?: number;
        role?: string;
        username?: string;
        email?: string;
    };
};

export type User = {
    id?: number;
    fname: string;
    lname: string;
    email: string;
    gender?: 'male' | 'female';
    user_type: UserType;
    status?: UserStatus;
    biometric_enrollment_status?: BiometricEnrollmentStatus;
    /**
     * role id for privileged staff
     */
    role_id?: number;
    /**
     * current class of the student
     */
    class_id?: number;
    regno?: string;
    username?: string;
    password?: string;
};

export type UserCreate = User;

export type UserResponse = {
    id?: number;
    name?: string;
    email?: string;
    gender?: 'male' | 'female';
    status?: UserStatus;
    biometric_enrollment_status?: BiometricEnrollmentStatus;
    role?: string;
    class?: string;
    studentregno?: string;
    username?: string;
};

export type Role = {
    role_name: string;
    description?: string;
};

export type RoleResponse = Role & {
    id?: number;
};

export type Branch = {
    name: string;
    location?: string;
    description?: string;
    status?: 'active' | 'revoked';
};

export type BranchResponse = Branch & {
    id?: number;
    admin_id?: number;
    date_created?: string;
};

export type Group = {
    branch_id: number;
    grouptype_id: number;
    name: string;
    expected_weekly_hours?: number;
    absence_threshold: number;
    supervisors?: Array<{
        user_id?: number;
    }>;
};

export type GroupResponse = Group & {
    id?: number;
    date_created?: string;
};

export type Subgroup = {
    group_id: number;
    name: string;
    absence_threshold: number;
    created_by?: number;
};

export type SubgroupResponse = Subgroup & {
    id?: number;
    date_created?: string;
};

export type PermissionRequest = {
    permissiontype_id?: number;
    user_id?: number;
    /**
     * The admin or HR who initiated this permission
     */
    initiatedby?: number;
    reason?: string;
    start_date?: string;
    end_date?: string;
    status?: 'pending' | 'approved' | 'rejected';
    /**
     * The stored file name (optional)
     */
    additional_proof?: string;
    requested_at?: string;
};

export type PermissionApproval = {
    permission_id?: number;
    approver_id?: number;
    remark?: string;
    status?: 'pending' | 'approved' | 'rejected';
};

export type Annoucement = {
    name?: string;
    message?: string;
    /**
     * The date, time the annoucement will be visible to its respective groups/subgroups - terminals
     */
    start_datetime?: string;
    /**
     * The date, time the annoucement will be disappear to its respective groups/subgroups - terminals
     */
    end_datetime?: string;
    /**
     * The admin who created the announcement
     */
    created_by?: number;
};

export type AnnouncementResponse = Annoucement & {
    id?: number;
    date_created?: string;
};

export type Event = {
    name?: string;
    /**
     * Target group (exclusive with subgroup_id)
     */
    group_id?: number | null;
    /**
     * Target subgroup (exclusive with group_id)
     */
    subgroup_id?: number | null;
    start_datetime?: string;
    end_datetime?: string;
    affects_attendance?: boolean;
    /**
     * 1 = check-in only
     * 2 = check-in and check-out
     *
     */
    handshake?: 1 | 2;
    created_by?: number;
};

export type EventCheckinCheckoutRange = {
    checkin_start_datetime?: string;
    checkin_end_datetime?: string;
    checkout_start_datetime?: string | null;
    checkout_end_datetime?: string | null;
};

export type EventCreate = Event & {
    /**
     * check-in/check-out range for this event
     */
    checkin_ranges?: EventCheckinCheckoutRange;
};

export type EventResponse = Event & {
    id?: number;
};

export type Exception = {
    exception_type_id?: number;
    description?: string;
    start_date?: string;
    end_date?: string;
    /**
     * The admin who created the exception
     */
    created_by?: number;
};

export type ExceptionResponse = Exception & {
    id?: number;
};

export type Terminal = {
    name?: string;
    /**
     * Auto generated by the system
     */
    activation_code?: string;
    branch_id?: number;
    slug?: string;
    status?: 'pending' | 'active' | 'revoked';
};

export type TerminalAuthTypes = 'face' | 'card' | 'fingerprint';

/**
 * This defines the type of auth supported by the terminal
 */
export type TerminalCapabilities = {
    /**
     * reference to the terminal auth types
     */
    auth_type_id: number;
    auth_step: number;
};

/**
 * groups/subgroups allowed to auth at this terminal
 */
export type TerminalAccessPolicy = {
    group_id?: number;
    subgroup_id?: number;
    auth_type_id?: number;
};

export type TerminalCreate = Terminal & {
    /**
     * The supported auth types for this terminal
     */
    auth_capabilities?: Array<TerminalCapabilities>;
    access_policy?: Array<TerminalAccessPolicy>;
};

export type TerminalResponse = Terminal & {
    id?: number;
    date_created?: string;
};

export type BiometricFaceEnrollRequest = {
    user_id: number;
    /**
     * Base64 encoded face image
     */
    face_image: string;
};

export type BiometricFaceEnrollResponse = {
    message: string;
    biometric_profile_id: number;
};

export type BiometricFaceVerifyRequest = {
    terminal_id: number;
    face_image: string;
};

export type BiometricFaceVerifyResponse = {
    matched: boolean;
    user_id?: number | null;
    confidence_score?: number;
    message?: string;
};

export type AttendanceStatus = {
    name?: 'present' | 'absent' | 'late' | 'on permission';
};

/**
 * track progress throughout the auth sequence
 */
export type TerminalAuthSession = {
    user_id?: number;
    terminal_id?: number;
    /**
     * Since most terminals are presummed to support atleast 2 auth types,
     * the current step will help track the progress to ensure that the user completes all the terminal required auth types
     * before there are dimmed to have completed an auth session( check-in or check-out)
     *
     */
    current_step?: number;
    status?: 'in_progress' | 'completed';
};

/**
 * logs each auth attemp, ie record is created for each completed auth session
 */
export type TerminalAuthLog = {
    user_id?: number;
    terminal_id?: number;
    attendance_context?: 'daily' | 'event';
    event_id?: number;
    auth_type_id?: number;
};

/**
 * Represents attendance after auth successs
 * ie upon successfull checkin and checkout for daily attendance
 * or checkin and/or checkout for event attendance depending on the handshake
 *
 */
export type TerminalAttendanceSession = {
    user_id?: number;
    terminal_id?: number;
    attendance_context?: 'daily' | 'event';
    event_id?: number;
    checkin_timestamp?: string;
    checkout_timestamp?: string;
    checkin_status?: 'on time' | 'late';
    checkout_status?: 'on time' | 'early';
    session_status?: 'active' | 'completed' | 'missed checkout';
    sync_status?: 'pending' | 'synced' | 'error';
};

/**
 * Summary of the daily/event attendance, this is the record that get sync to the central db
 * Was the user present, late or on permission for this day
 *
 */
export type TerminalAttendanceSummary = {
    user_id?: number;
    terminal_id?: number;
    attendance_date?: string;
    attendance_context?: 'daily' | 'event';
    event_id?: number;
    first_checkin?: string;
    last_checkout?: string;
    /**
     * Time difference in int btn last checkout and first checkin
     */
    total_hours?: number;
    attendance_status?: number;
    /**
     * useful when the user is on a permission, so we do not have to compute the attendance session to arive to get the summary
     */
    derived_from_session?: boolean;
};

export type TerminalAuthCreate = TerminalAuthSession & {
    terminal_auth_log?: TerminalAuthLog & {
        [key: string]: unknown;
    };
};

export type TerminalAuthInProgressResponse = {
    status: 'in_progress';
    current_step: number;
    next_auth_type_id: number;
};

export type TerminalAuthCompletedResponse = {
    status: 'completed';
    message?: string;
    attendance_session: TerminalAttendanceSession;
};

export type TerminalAttendanceSummaryCreate = TerminalAttendanceSummary & {
    [key: string]: unknown;
};

export type Logs = {
    category?: string;
    description?: string;
    user_id?: number;
};

export type LoginData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type LoginResponses = {
    /**
     * successful login
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type LogoutResponses = {
    /**
     * logout successful
     */
    200: {
        success?: boolean;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type RefreshResponses = {
    /**
     * refresh access token
     */
    200: LoginResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by user type
         */
        user_type?: UserType;
        /**
         * Filter by status
         */
        status?: UserStatus;
    };
    url: '/api/v1/users';
};

export type ListUsersErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListUsersResponses = {
    /**
     * List of users
     */
    200: Array<UserResponse>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    /**
     * Ensure you insert into staff tbl specifying the role and of the staff if the user type is staff
     */
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type CreateUserErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateUserResponses = {
    /**
     * User created successfully
     */
    201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DeleteUserResponses = {
    /**
     * User deleted successfully
     */
    200: unknown;
};

export type GetUserByIdData = {
    body?: never;
    path: {
        /**
         * The unique ID of the user
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type GetUserByIdErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type GetUserByIdResponses = {
    /**
     * User found
     */
    200: UserResponse;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserData = {
    body: UserCreate;
    path: {
        /**
         * The unique ID of the user
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateUserResponses = {
    /**
     * User updated successfully
     */
    200: UserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/roles';
};

export type ListRolesErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListRolesResponses = {
    /**
     * Roles list
     */
    200: Array<RoleResponse>;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type ListBranchesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/branches';
};

export type ListBranchesErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListBranchesResponses = {
    /**
     * List of branches
     */
    200: Array<BranchResponse>;
};

export type ListBranchesResponse = ListBranchesResponses[keyof ListBranchesResponses];

export type CreateBranchData = {
    body: Branch & {
        /**
         * branch admin
         */
        user_id?: number;
    };
    path?: never;
    query?: never;
    url: '/api/v1/branches';
};

export type CreateBranchErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateBranchResponses = {
    /**
     * Branch created successfully
     */
    201: BranchResponse;
};

export type CreateBranchResponse = CreateBranchResponses[keyof CreateBranchResponses];

export type UpdateBranchData = {
    body?: Branch & {
        user_id?: number;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/branches/{id}';
};

export type UpdateBranchErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type UpdateBranchResponses = {
    /**
     * Branch updated successfully
     */
    200: unknown;
};

export type CreateGroupTypeData = {
    body: {
        name: string;
        abbreviation?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/groups/group_type';
};

export type CreateGroupTypeErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateGroupTypeResponses = {
    /**
     * Group type created successfully
     */
    201: unknown;
};

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/groups';
};

export type ListGroupsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListGroupsResponses = {
    /**
     * Groups list
     */
    200: Array<GroupResponse>;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: Group;
    path?: never;
    query?: never;
    url: '/api/v1/groups';
};

export type CreateGroupErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateGroupResponses = {
    /**
     * Group created
     */
    201: unknown;
};

export type AssignUsersToGroupData = {
    body?: {
        group_id?: number;
        user_ids?: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/groups/members';
};

export type AssignUsersToGroupErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type AssignUsersToGroupResponses = {
    /**
     * Users assigned to group
     */
    200: unknown;
};

export type ListSubgroupsData = {
    body?: never;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/api/v1/groups/{groupId}/subgroups';
};

export type ListSubgroupsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListSubgroupsResponses = {
    /**
     * Subgroup list
     */
    200: unknown;
};

export type CreateSubgroupData = {
    body?: Subgroup;
    path: {
        groupId: number;
    };
    query?: never;
    url: '/api/v1/groups/{groupId}/subgroups';
};

export type CreateSubgroupErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateSubgroupResponses = {
    /**
     * Subgroup created
     */
    201: unknown;
};

export type AssignUsersToSubgroupData = {
    body?: {
        subgroup_id?: number;
        user_ids?: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/subgroups/member';
};

export type AssignUsersToSubgroupErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type AssignUsersToSubgroupResponses = {
    /**
     * Users assigned to subgroup
     */
    200: unknown;
};

export type CreatePermissionRequestData = {
    body: PermissionRequest & {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/permissions';
};

export type CreatePermissionRequestErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreatePermissionRequestResponses = {
    /**
     * Permission request created
     */
    201: unknown;
};

export type DecidePermissionRequestData = {
    body: PermissionApproval & {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/permissions/decision';
};

export type DecidePermissionRequestErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type DecidePermissionRequestResponses = {
    /**
     * Permission decision recorded
     */
    200: unknown;
};

export type ListAnnouncementsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If provided, returns pending announcements for the specified group.
         */
        group_id?: number;
        /**
         * If provided, returns pending announcements for the specified subgroup.
         */
        subgroup_id?: number;
    };
    url: '/api/v1/announcement';
};

export type ListAnnouncementsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListAnnouncementsResponses = {
    /**
     * List of events (optionally filtered by group or subgroup)
     */
    200: Array<AnnouncementResponse>;
};

export type ListAnnouncementsResponse = ListAnnouncementsResponses[keyof ListAnnouncementsResponses];

export type CreateAnnouncementData = {
    body: Annoucement & {
        /**
         * Target groups
         */
        group_id: Array<number>;
        /**
         * Target subgroups
         */
        subgroup_id: Array<number>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/announcement';
};

export type CreateAnnouncementErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateAnnouncementResponses = {
    /**
     * Annoucement created successfully
     */
    200: unknown;
};

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If provided, returns pending events for the specified group.
         */
        group_id?: number;
        /**
         * If provided, returns pending events for the specified subgroup.
         */
        subgroup_id?: number;
    };
    url: '/api/v1/events';
};

export type ListEventsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListEventsResponses = {
    /**
     * List of events (optionally filtered by group or subgroup)
     */
    200: Array<EventResponse>;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type CreateEventData = {
    body: EventCreate;
    path?: never;
    query?: never;
    url: '/api/v1/events';
};

export type CreateEventErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateEventResponses = {
    /**
     * Event created successfully
     */
    200: unknown;
};

export type ListExceptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/exceptions';
};

export type ListExceptionsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListExceptionsResponses = {
    /**
     * List of exceptions
     */
    200: Array<ExceptionResponse>;
};

export type ListExceptionsResponse = ListExceptionsResponses[keyof ListExceptionsResponses];

export type CreateExceptionData = {
    body: Exception;
    path?: never;
    query?: never;
    url: '/api/v1/exceptions';
};

export type CreateExceptionErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateExceptionResponses = {
    /**
     * Exception created successfully
     */
    200: unknown;
};

export type CreateTerminalData = {
    body: TerminalCreate;
    path?: never;
    query?: never;
    url: '/api/v1/terminals';
};

export type CreateTerminalErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CreateTerminalResponses = {
    /**
     * Terminal created successfully
     */
    200: unknown;
};

export type ListTerminalsData = {
    body?: never;
    path: {
        branchid: number;
    };
    query?: never;
    url: '/api/v1/terminals/${branchid}';
};

export type ListTerminalsErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ListTerminalsResponses = {
    /**
     * List of all terminals at that branch
     */
    200: Array<TerminalCreate>;
};

export type ListTerminalsResponse = ListTerminalsResponses[keyof ListTerminalsResponses];

export type TerminalCapabilitiesData = {
    body?: never;
    path: {
        terminalId: number;
    };
    query?: never;
    url: '/api/v1/terminals/{terminalId}';
};

export type TerminalCapabilitiesErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type TerminalCapabilitiesResponses = {
    /**
     * List the auth types supported by this terminal
     */
    200: Array<TerminalCreate>;
};

export type TerminalCapabilitiesResponse = TerminalCapabilitiesResponses[keyof TerminalCapabilitiesResponses];

export type TerminalAuthData = {
    body: TerminalAuthCreate;
    path?: never;
    query?: never;
    url: '/api/v1/terminals/auth';
};

export type TerminalAuthErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type TerminalAuthResponses = {
    /**
     * Authentication successful, if there are more auth types to complete, the response will indicate
     */
    200: TerminalAuthInProgressResponse | TerminalAuthCompletedResponse;
};

export type TerminalAuthResponse = TerminalAuthResponses[keyof TerminalAuthResponses];

export type SyncAttendanceSummaryData = {
    body: Array<TerminalAttendanceSummaryCreate>;
    path?: never;
    query?: never;
    url: '/api/v1/attendance/sync';
};

export type SyncAttendanceSummaryErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type SyncAttendanceSummaryResponses = {
    /**
     * Attendance summary synced
     */
    200: {
        message?: string;
    } | {
        message?: string;
        failed_records?: Array<{
            user_id?: number;
            terminal_id?: number;
            attendance_date?: string;
            attendance_context?: string;
            attendance_status?: number;
            error_message?: string;
        }>;
    };
};

export type SyncAttendanceSummaryResponse = SyncAttendanceSummaryResponses[keyof SyncAttendanceSummaryResponses];

export type FaceEnrollmentData = {
    body: BiometricFaceEnrollRequest;
    path?: never;
    query?: never;
    url: '/api/v1/biometric/face/enroll';
};

export type FaceEnrollmentErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type FaceEnrollmentResponses = {
    /**
     * face enrollment successfull
     */
    200: BiometricFaceEnrollResponse;
};

export type FaceEnrollmentResponse = FaceEnrollmentResponses[keyof FaceEnrollmentResponses];

export type FaceVerificationData = {
    body: BiometricFaceVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/biometric/face/verify';
};

export type FaceVerificationErrors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized - Invalid or missing token
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type FaceVerificationResponses = {
    /**
     * face verification result
     */
    200: BiometricFaceVerifyResponse;
};

export type FaceVerificationResponse = FaceVerificationResponses[keyof FaceVerificationResponses];
