// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { enrollFaceEnrollFacePost, healthCheckHealthGet, type Options, verifyFaceVerifyPost } from '../sdk.gen';
import type { EnrollFaceEnrollFacePostData, EnrollFaceEnrollFacePostError, HealthCheckHealthGetData, VerifyFaceVerifyPostData, VerifyFaceVerifyPostError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthCheckHealthGetQueryKey = (options?: Options<HealthCheckHealthGetData>) => createQueryKey('healthCheckHealthGet', options);

/**
 * Health Check
 *
 * Health check
 */
export const healthCheckHealthGetOptions = (options?: Options<HealthCheckHealthGetData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof healthCheckHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckHealthGetQueryKey(options)
});

/**
 * Enroll Face
 */
export const enrollFaceEnrollFacePostMutation = (options?: Partial<Options<EnrollFaceEnrollFacePostData>>): UseMutationOptions<unknown, AxiosError<EnrollFaceEnrollFacePostError>, Options<EnrollFaceEnrollFacePostData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<EnrollFaceEnrollFacePostError>, Options<EnrollFaceEnrollFacePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await enrollFaceEnrollFacePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Verify Face
 */
export const verifyFaceVerifyPostMutation = (options?: Partial<Options<VerifyFaceVerifyPostData>>): UseMutationOptions<unknown, AxiosError<VerifyFaceVerifyPostError>, Options<VerifyFaceVerifyPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<VerifyFaceVerifyPostError>, Options<VerifyFaceVerifyPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await verifyFaceVerifyPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
