// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { centralOpenapiActivateTerminal, openapiEnrollFaceEnrollFacePost, openapiHealthCheckHealthGet, openapiVerifyFaceVerifyPost, type Options } from '../sdk.gen';
import type { CentralOpenapiActivateTerminalData, CentralOpenapiActivateTerminalResponse, OpenapiEnrollFaceEnrollFacePostData, OpenapiEnrollFaceEnrollFacePostError, OpenapiHealthCheckHealthGetData, OpenapiVerifyFaceVerifyPostData, OpenapiVerifyFaceVerifyPostError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const openapiHealthCheckHealthGetQueryKey = (options?: Options<OpenapiHealthCheckHealthGetData>) => createQueryKey('openapiHealthCheckHealthGet', options);

/**
 * Health Check
 *
 * Health check
 */
export const openapiHealthCheckHealthGetOptions = (options?: Options<OpenapiHealthCheckHealthGetData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof openapiHealthCheckHealthGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await openapiHealthCheckHealthGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: openapiHealthCheckHealthGetQueryKey(options)
});

/**
 * Enroll Face
 */
export const openapiEnrollFaceEnrollFacePostMutation = (options?: Partial<Options<OpenapiEnrollFaceEnrollFacePostData>>): UseMutationOptions<unknown, AxiosError<OpenapiEnrollFaceEnrollFacePostError>, Options<OpenapiEnrollFaceEnrollFacePostData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<OpenapiEnrollFaceEnrollFacePostError>, Options<OpenapiEnrollFaceEnrollFacePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await openapiEnrollFaceEnrollFacePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Verify Face
 */
export const openapiVerifyFaceVerifyPostMutation = (options?: Partial<Options<OpenapiVerifyFaceVerifyPostData>>): UseMutationOptions<unknown, AxiosError<OpenapiVerifyFaceVerifyPostError>, Options<OpenapiVerifyFaceVerifyPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<OpenapiVerifyFaceVerifyPostError>, Options<OpenapiVerifyFaceVerifyPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await openapiVerifyFaceVerifyPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Activate Terminal
 */
export const centralOpenapiActivateTerminalMutation = (options?: Partial<Options<CentralOpenapiActivateTerminalData>>): UseMutationOptions<CentralOpenapiActivateTerminalResponse, AxiosError<DefaultError>, Options<CentralOpenapiActivateTerminalData>> => {
    const mutationOptions: UseMutationOptions<CentralOpenapiActivateTerminalResponse, AxiosError<DefaultError>, Options<CentralOpenapiActivateTerminalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await centralOpenapiActivateTerminal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
