// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CentralOpenapiActivateTerminalData, CentralOpenapiActivateTerminalResponses, OpenapiEnrollFaceEnrollFacePostData, OpenapiEnrollFaceEnrollFacePostErrors, OpenapiEnrollFaceEnrollFacePostResponses, OpenapiHealthCheckHealthGetData, OpenapiHealthCheckHealthGetResponses, OpenapiVerifyFaceVerifyPostData, OpenapiVerifyFaceVerifyPostErrors, OpenapiVerifyFaceVerifyPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Health check
 */
export const openapiHealthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<OpenapiHealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<OpenapiHealthCheckHealthGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
});

/**
 * Enroll Face
 */
export const openapiEnrollFaceEnrollFacePost = <ThrowOnError extends boolean = false>(options: Options<OpenapiEnrollFaceEnrollFacePostData, ThrowOnError>) => (options.client ?? client).post<OpenapiEnrollFaceEnrollFacePostResponses, OpenapiEnrollFaceEnrollFacePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/enroll-face',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Verify Face
 */
export const openapiVerifyFaceVerifyPost = <ThrowOnError extends boolean = false>(options: Options<OpenapiVerifyFaceVerifyPostData, ThrowOnError>) => (options.client ?? client).post<OpenapiVerifyFaceVerifyPostResponses, OpenapiVerifyFaceVerifyPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/verify',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Activate Terminal
 */
export const centralOpenapiActivateTerminal = <ThrowOnError extends boolean = false>(options: Options<CentralOpenapiActivateTerminalData, ThrowOnError>) => (options.client ?? client).post<CentralOpenapiActivateTerminalResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/central/terminal/activate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
