// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { EnrollFaceEnrollFacePostData, EnrollFaceEnrollFacePostErrors, EnrollFaceEnrollFacePostResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, VerifyFaceVerifyPostData, VerifyFaceVerifyPostErrors, VerifyFaceVerifyPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Health check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
});

/**
 * Enroll Face
 */
export const enrollFaceEnrollFacePost = <ThrowOnError extends boolean = false>(options: Options<EnrollFaceEnrollFacePostData, ThrowOnError>) => (options.client ?? client).post<EnrollFaceEnrollFacePostResponses, EnrollFaceEnrollFacePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    url: '/enroll-face',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Verify Face
 */
export const verifyFaceVerifyPost = <ThrowOnError extends boolean = false>(options: Options<VerifyFaceVerifyPostData, ThrowOnError>) => (options.client ?? client).post<VerifyFaceVerifyPostResponses, VerifyFaceVerifyPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/verify',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
