// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_enroll_face_enroll_face_post
 */
export type BodyEnrollFaceEnrollFacePost = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Image
     */
    image: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyRequest
 */
export type VerifyRequest = {
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Image
     */
    image: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EnrollFaceEnrollFacePostData = {
    body: BodyEnrollFaceEnrollFacePost;
    path?: never;
    query?: never;
    url: '/enroll-face';
};

export type EnrollFaceEnrollFacePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnrollFaceEnrollFacePostError = EnrollFaceEnrollFacePostErrors[keyof EnrollFaceEnrollFacePostErrors];

export type EnrollFaceEnrollFacePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyFaceVerifyPostData = {
    body: VerifyRequest;
    path?: never;
    query?: never;
    url: '/verify';
};

export type VerifyFaceVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyFaceVerifyPostError = VerifyFaceVerifyPostErrors[keyof VerifyFaceVerifyPostErrors];

export type VerifyFaceVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
