// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_enroll_face_enroll_face_post
 */
export type OpenapiBodyEnrollFaceEnrollFacePost = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Image
     */
    image: string;
};

/**
 * HTTPValidationError
 */
export type OpenapiHttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<OpenapiValidationError>;
};

/**
 * ValidationError
 */
export type OpenapiValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyRequest
 */
export type OpenapiVerifyRequest = {
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Image
     */
    image: string;
};

export type CentralOpenapiActivationResponse = {
    success?: boolean;
    data?: CentralOpenapiTerminalData;
};

export type CentralOpenapiTerminalData = {
    id?: number;
    name?: string;
    slug?: string;
    branch_id?: number;
    branch?: string;
    status?: string;
    auth_capabilities?: Array<CentralOpenapiAuthCapability>;
    access_policy?: Array<CentralOpenapiAccessPolicy>;
    members?: Array<CentralOpenapiMember>;
};

export type CentralOpenapiAuthCapability = {
    auth_type_name?: string;
    auth_step?: number;
};

export type CentralOpenapiAccessPolicy = {
    group_name?: string;
    auth_type_name?: string;
};

export type CentralOpenapiMember = {
    id?: number;
    fname?: string;
    lname?: string;
    face_template?: string;
    fingerprint_template?: string;
};

export type OpenapiHealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type OpenapiHealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OpenapiEnrollFaceEnrollFacePostData = {
    body: OpenapiBodyEnrollFaceEnrollFacePost;
    path?: never;
    query?: never;
    url: '/enroll-face';
};

export type OpenapiEnrollFaceEnrollFacePostErrors = {
    /**
     * Validation Error
     */
    422: OpenapiHttpValidationError;
};

export type OpenapiEnrollFaceEnrollFacePostError = OpenapiEnrollFaceEnrollFacePostErrors[keyof OpenapiEnrollFaceEnrollFacePostErrors];

export type OpenapiEnrollFaceEnrollFacePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OpenapiVerifyFaceVerifyPostData = {
    body: OpenapiVerifyRequest;
    path?: never;
    query?: never;
    url: '/verify';
};

export type OpenapiVerifyFaceVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: OpenapiHttpValidationError;
};

export type OpenapiVerifyFaceVerifyPostError = OpenapiVerifyFaceVerifyPostErrors[keyof OpenapiVerifyFaceVerifyPostErrors];

export type OpenapiVerifyFaceVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CentralOpenapiActivateTerminalData = {
    body: {
        code: string;
    };
    path?: never;
    query?: never;
    url: '/central/terminal/activate';
};

export type CentralOpenapiActivateTerminalResponses = {
    /**
     * Successful Activation
     */
    200: CentralOpenapiActivationResponse;
};

export type CentralOpenapiActivateTerminalResponse = CentralOpenapiActivateTerminalResponses[keyof CentralOpenapiActivateTerminalResponses];
