// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { assignUsersToGroup, assignUsersToSubgroup, createAnnouncement, createBranch, createEvent, createException, createGroup, createGroupType, createPermissionRequest, createSubgroup, createTerminal, createUser, decidePermissionRequest, deleteUser, faceEnrollment, faceVerification, getUserById, listAnnouncements, listBranches, listEvents, listExceptions, listGroups, listRoles, listSubgroups, listTerminals, listUsers, login, logout, type Options, refresh, syncAttendanceSummary, terminalAuth, terminalCapabilities, updateBranch, updateUser } from '../sdk.gen';
import type { AssignUsersToGroupData, AssignUsersToSubgroupData, CreateAnnouncementData, CreateBranchData, CreateBranchResponse, CreateEventData, CreateExceptionData, CreateGroupData, CreateGroupTypeData, CreatePermissionRequestData, CreateSubgroupData, CreateTerminalData, CreateUserData, CreateUserResponse, DecidePermissionRequestData, DeleteUserData, FaceEnrollmentData, FaceEnrollmentResponse, FaceVerificationData, FaceVerificationResponse, GetUserByIdData, GetUserByIdResponse, ListAnnouncementsData, ListAnnouncementsResponse, ListBranchesData, ListBranchesResponse, ListEventsData, ListEventsResponse, ListExceptionsData, ListExceptionsResponse, ListGroupsData, ListGroupsResponse, ListRolesData, ListRolesResponse, ListSubgroupsData, ListTerminalsData, ListTerminalsResponse, ListUsersData, ListUsersResponse, LoginData, LoginResponse2, LogoutData, LogoutResponse, RefreshData, RefreshResponse, SyncAttendanceSummaryData, SyncAttendanceSummaryResponse, TerminalAuthData, TerminalAuthResponse, TerminalCapabilitiesData, TerminalCapabilitiesResponse, UpdateBranchData, UpdateUserData, UpdateUserResponse } from '../types.gen';

/**
 * login admin users
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse2, AxiosError<DefaultError>, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse2, AxiosError<DefaultError>, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * logou admin users
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * refresh access token
 */
export const refreshMutation = (options?: Partial<Options<RefreshData>>): UseMutationOptions<RefreshResponse, AxiosError<DefaultError>, Options<RefreshData>> => {
    const mutationOptions: UseMutationOptions<RefreshResponse, AxiosError<DefaultError>, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

/**
 * List all users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse, AxiosError<DefaultError>, ListUsersResponse, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});

/**
 * Create a new user
 */
export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<CreateUserResponse, AxiosError<DefaultError>, Options<CreateUserData>> => {
    const mutationOptions: UseMutationOptions<CreateUserResponse, AxiosError<DefaultError>, Options<CreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a user
 */
export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) => createQueryKey('getUserById', options);

/**
 * Get a user by ID
 */
export const getUserByIdOptions = (options: Options<GetUserByIdData>) => queryOptions<GetUserByIdResponse, AxiosError<DefaultError>, GetUserByIdResponse, ReturnType<typeof getUserByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserByIdQueryKey(options)
});

/**
 * Update a user
 */
export const updateUserMutation = (options?: Partial<Options<UpdateUserData>>): UseMutationOptions<UpdateUserResponse, AxiosError<DefaultError>, Options<UpdateUserData>> => {
    const mutationOptions: UseMutationOptions<UpdateUserResponse, AxiosError<DefaultError>, Options<UpdateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRolesQueryKey = (options?: Options<ListRolesData>) => createQueryKey('listRoles', options);

/**
 * List all roles
 */
export const listRolesOptions = (options?: Options<ListRolesData>) => queryOptions<ListRolesResponse, AxiosError<DefaultError>, ListRolesResponse, ReturnType<typeof listRolesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRoles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRolesQueryKey(options)
});

export const listBranchesQueryKey = (options?: Options<ListBranchesData>) => createQueryKey('listBranches', options);

/**
 * List all branchs
 */
export const listBranchesOptions = (options?: Options<ListBranchesData>) => queryOptions<ListBranchesResponse, AxiosError<DefaultError>, ListBranchesResponse, ReturnType<typeof listBranchesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listBranches({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listBranchesQueryKey(options)
});

/**
 * Create a new branch
 *
 * Creat a new branch or campus within the institution
 */
export const createBranchMutation = (options?: Partial<Options<CreateBranchData>>): UseMutationOptions<CreateBranchResponse, AxiosError<DefaultError>, Options<CreateBranchData>> => {
    const mutationOptions: UseMutationOptions<CreateBranchResponse, AxiosError<DefaultError>, Options<CreateBranchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createBranch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update branch details
 */
export const updateBranchMutation = (options?: Partial<Options<UpdateBranchData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdateBranchData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<UpdateBranchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateBranch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a group type
 */
export const createGroupTypeMutation = (options?: Partial<Options<CreateGroupTypeData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateGroupTypeData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateGroupTypeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createGroupType({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listGroupsQueryKey = (options?: Options<ListGroupsData>) => createQueryKey('listGroups', options);

/**
 * List all groups
 */
export const listGroupsOptions = (options?: Options<ListGroupsData>) => queryOptions<ListGroupsResponse, AxiosError<DefaultError>, ListGroupsResponse, ReturnType<typeof listGroupsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listGroups({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listGroupsQueryKey(options)
});

/**
 * Create a group (class / department)
 */
export const createGroupMutation = (options?: Partial<Options<CreateGroupData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateGroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Assign users to a group
 */
export const assignUsersToGroupMutation = (options?: Partial<Options<AssignUsersToGroupData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AssignUsersToGroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AssignUsersToGroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assignUsersToGroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listSubgroupsQueryKey = (options: Options<ListSubgroupsData>) => createQueryKey('listSubgroups', options);

/**
 * List subgroups under a group
 */
export const listSubgroupsOptions = (options: Options<ListSubgroupsData>) => queryOptions<unknown, AxiosError<DefaultError>, unknown, ReturnType<typeof listSubgroupsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listSubgroups({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listSubgroupsQueryKey(options)
});

/**
 * Create a subgroup
 */
export const createSubgroupMutation = (options?: Partial<Options<CreateSubgroupData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateSubgroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateSubgroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSubgroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Assign users to a subgroup
 */
export const assignUsersToSubgroupMutation = (options?: Partial<Options<AssignUsersToSubgroupData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AssignUsersToSubgroupData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<AssignUsersToSubgroupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await assignUsersToSubgroup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create permission request for a user
 */
export const createPermissionRequestMutation = (options?: Partial<Options<CreatePermissionRequestData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreatePermissionRequestData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreatePermissionRequestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPermissionRequest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Approve or reject a permission request
 */
export const decidePermissionRequestMutation = (options?: Partial<Options<DecidePermissionRequestData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DecidePermissionRequestData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<DecidePermissionRequestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await decidePermissionRequest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listAnnouncementsQueryKey = (options?: Options<ListAnnouncementsData>) => createQueryKey('listAnnouncements', options);

/**
 * Get all announcements or filter by group or subgroup ID
 */
export const listAnnouncementsOptions = (options?: Options<ListAnnouncementsData>) => queryOptions<ListAnnouncementsResponse, AxiosError<DefaultError>, ListAnnouncementsResponse, ReturnType<typeof listAnnouncementsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAnnouncements({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAnnouncementsQueryKey(options)
});

/**
 * Create an announcement
 */
export const createAnnouncementMutation = (options?: Partial<Options<CreateAnnouncementData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateAnnouncementData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateAnnouncementData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createAnnouncement({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listEventsQueryKey = (options?: Options<ListEventsData>) => createQueryKey('listEvents', options);

/**
 * Get all events or filter by group or subgroup ID
 */
export const listEventsOptions = (options?: Options<ListEventsData>) => queryOptions<ListEventsResponse, AxiosError<DefaultError>, ListEventsResponse, ReturnType<typeof listEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEventsQueryKey(options)
});

/**
 * Create an event
 */
export const createEventMutation = (options?: Partial<Options<CreateEventData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateEventData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateEventData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEvent({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listExceptionsQueryKey = (options?: Options<ListExceptionsData>) => createQueryKey('listExceptions', options);

/**
 * Get all exceptions
 */
export const listExceptionsOptions = (options?: Options<ListExceptionsData>) => queryOptions<ListExceptionsResponse, AxiosError<DefaultError>, ListExceptionsResponse, ReturnType<typeof listExceptionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listExceptions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listExceptionsQueryKey(options)
});

/**
 * Create an exception
 */
export const createExceptionMutation = (options?: Partial<Options<CreateExceptionData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateExceptionData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateExceptionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createException({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * create a terminal
 */
export const createTerminalMutation = (options?: Partial<Options<CreateTerminalData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateTerminalData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<CreateTerminalData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTerminal({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listTerminalsQueryKey = (options: Options<ListTerminalsData>) => createQueryKey('listTerminals', options);

/**
 * List all terminals at a particular branch
 */
export const listTerminalsOptions = (options: Options<ListTerminalsData>) => queryOptions<ListTerminalsResponse, AxiosError<DefaultError>, ListTerminalsResponse, ReturnType<typeof listTerminalsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTerminals({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTerminalsQueryKey(options)
});

export const terminalCapabilitiesQueryKey = (options: Options<TerminalCapabilitiesData>) => createQueryKey('terminalCapabilities', options);

/**
 * Get the auth types,policy supported by the terminal
 */
export const terminalCapabilitiesOptions = (options: Options<TerminalCapabilitiesData>) => queryOptions<TerminalCapabilitiesResponse, AxiosError<DefaultError>, TerminalCapabilitiesResponse, ReturnType<typeof terminalCapabilitiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await terminalCapabilities({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: terminalCapabilitiesQueryKey(options)
});

/**
 * Authenticate at a terminal
 */
export const terminalAuthMutation = (options?: Partial<Options<TerminalAuthData>>): UseMutationOptions<TerminalAuthResponse, AxiosError<DefaultError>, Options<TerminalAuthData>> => {
    const mutationOptions: UseMutationOptions<TerminalAuthResponse, AxiosError<DefaultError>, Options<TerminalAuthData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await terminalAuth({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sync attendance summary to central database
 */
export const syncAttendanceSummaryMutation = (options?: Partial<Options<SyncAttendanceSummaryData>>): UseMutationOptions<SyncAttendanceSummaryResponse, AxiosError<DefaultError>, Options<SyncAttendanceSummaryData>> => {
    const mutationOptions: UseMutationOptions<SyncAttendanceSummaryResponse, AxiosError<DefaultError>, Options<SyncAttendanceSummaryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await syncAttendanceSummary({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Enroll face biometric profile
 */
export const faceEnrollmentMutation = (options?: Partial<Options<FaceEnrollmentData>>): UseMutationOptions<FaceEnrollmentResponse, AxiosError<DefaultError>, Options<FaceEnrollmentData>> => {
    const mutationOptions: UseMutationOptions<FaceEnrollmentResponse, AxiosError<DefaultError>, Options<FaceEnrollmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await faceEnrollment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Authenticate user via face recognition
 */
export const faceVerificationMutation = (options?: Partial<Options<FaceVerificationData>>): UseMutationOptions<FaceVerificationResponse, AxiosError<DefaultError>, Options<FaceVerificationData>> => {
    const mutationOptions: UseMutationOptions<FaceVerificationResponse, AxiosError<DefaultError>, Options<FaceVerificationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await faceVerification({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
