server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    
    # Point the entry dir
    root /var/www/public; 

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # Matches the service name in your docker-compose
        fastcgi_pass api:9000; 
        
        fastcgi_index index.php;
        include fastcgi_params;
        
        # This tells PHP exactly where index.php is
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
